### ISSUE TITLE
[BUG] `withImplementation` applies reusepolicy to interface, not implementation

### ISSUE THREAD

**Issue by quantummaiddeveloper** [quantummaid/injectmaid#34]
**Describe the bug**
`withImplementation` applies reusepolicy to interface, not implementation

**To Reproduce**
```java
var injector = anInjectMaid()
    .withImplementation(Interface1.class, Implementation.class, SINGLETON)
    .withImplementation(Interface2.class, Implementation.class, SINGLETON)
    .build();
assert injector.getInstance(Interface1.class) != injector.getInstance(Interface2.class);
```

**Expected behavior**
The two instances should be the same reference.

**Comment by lestephane** [comment]
Wouldn't this way be more explicit, making clear that n interfaces map to 1 implementation?

var injector = anInjectMaid().withImplementation(Implementation.class, SINGLETON, vararg ... interfaces)

**Comment by quantummaiddeveloper** [comment]
@lestephane created new issue #45
